 Reshaping operations are extremely important because the layers in a neural network only accept dimensional specific inputs.

In [1]:
import torch

In [21]:
a = torch.arange(12)
a= a.reshape([3, 4])

deduce the number of elements contained within the tensor. The number of elements inside a tensor (12 in our case) is equal to the product of the shape's component values.

In [14]:
torch.tensor(a.shape).prod(0)

tensor(12)

In [16]:
a.numel()

12

In [23]:
a.reshape(-1, 2)

tensor([[ 0,  1],
        [ 2,  3],
        [ 4,  5],
        [ 6,  7],
        [ 8,  9],
        [10, 11]])

The reshape function in PyTorch gives the output tensor with same values and number of elements as the input tensor, it only alters the shape of the output tensor.

In [41]:
a = torch.arange(9)

r = torch.reshape(a, (3,3))
print(f'Reshaped tensor: {r.shape}')
print(f'Tensor: {r}')

b = torch.tensor([[45, 56], [27, 34]])
torch.reshape(b, (-1,))

Reshaped tensor: torch.Size([3, 3])
Tensor: tensor([[0, 1, 2],
        [3, 4, 5],
        [6, 7, 8]])


tensor([45, 56, 27, 34])

In [42]:
print(r)
r.reshape(9,-1)

tensor([[0, 1, 2],
        [3, 4, 5],
        [6, 7, 8]])


tensor([[0],
        [1],
        [2],
        [3],
        [4],
        [5],
        [6],
        [7],
        [8]])

For example, a 4D tensor of shape (batch_size, height, width, channels) cannot be fed into a fully connected layer that only accepts two dimensions. So we need to reshape the tensor to represent something like (batch_size, height * width * channels) which is a 2D tensor that can be used as an input to the fully connected layer.

view() reshapes the tensor without copying memory

In [48]:
a = torch.rand(5, 4, 3, 2) # size (5, 4, 3, 2)
a_t = a.permute(0, 2, 3, 1) # size (5, 3, 2, 4)
print(a_t.shape)

q = a.stride()
print(q)

torch.Size([5, 3, 2, 4])
(24, 6, 2, 1)


Flatten Operation

The Flatten operation is used to convert a multi-dimensional tensor into a one-dimensional tensor. This is done by taking all the elements of the tensor and arranging them in a single dimension.

For example, if we have a tensor of shape (2, 3, 4), applying the Flatten operation would result in a tensor of shape (24,), which is basically a product of the individual elements.

Pytorch provides `view` & `flatten` functions to flatten tensors.

In [3]:
x = torch.randn(16, 5, 5, 3)
print(f'Original shape: {x.shape}')

x = x.view(16, 75) # ~ (16, 5*5*3)
print(f'Flattened shape: {x.shape}')

Original shape: torch.Size([16, 5, 5, 3])
Flattened shape: torch.Size([16, 75])


Using `flatten` function

In [ ]:
x = torch.randn(16, 5, 5, 3)
print(f'Original shape: {x.shape}')

x = x.flatten()
print(f'Flattened shape: {x.shape}')

This method creates a tensor x of shape of (16, 5, 5, 3) and then uses flatten function to reshape into 1D tensor. This gives us a tensor of shape (24,), which is product of dimensions of original tensor.

### Squeeze Operation
Removes dimensions of size 1 from a tensor. Useful when you have a tensor with unnecessary dimensions that you want to get rid off.

In [5]:
x = torch.randn(3, 1, 1, 5)
print(f'Original shape: {x.shape}')

x = x.squeeze()
print(f'Squeezed shape: {x.shape}')

Original shape: torch.Size([3, 1, 1, 5])
Squeezed shape: torch.Size([3, 5])


An advantage of this method is, the tensor can be unsqueezed again.

In [6]:
x = torch.randn(3, 5)
x = x.unsqueeze(1)
x = x.unsqueeze(2)
print(f'Unsqueezed shape: {x.shape}')

Unsqueezed shape: torch.Size([3, 1, 1, 5])


 it is possible to flatten only specific parts of a tensor. For example, suppose we have a tensor of shape [2,1,28,28] for a CNN. This means that we have a batch of 2 grayscale images with height and width dimensions of 28 x 28, respectively.

Here, we can specifically flatten the two images. To get the following shape: [2,1,784]. We could also squeeze off the channel axes to get the following shape: [2,784].

In [24]:
###  Concatenating tensors

t1 = torch.tensor([
    [1,2],
    [3,4]
])
t2 = torch.tensor([
    [5,6],
    [7,8]
])

Combine t1 and t2 row-wise (axis-0) in the following way

In [25]:
torch.cat((t1, t2), dim=0)

tensor([[1, 2],
        [3, 4],
        [5, 6],
        [7, 8]])

Combine them column-wise (axis-1) like this:

In [26]:
torch.cat((t1, t2), dim=1)

tensor([[1, 2, 5, 6],
        [3, 4, 7, 8]])

In [ ]:
# https://learn.microsoft.com/en-us/training/modules/intro-machine-learning-pytorch/2-tensors

%matplotlib inline
import torch
import numpy as np

In [ ]:
np_array = np.array(data)
x_np = torch.from_numpy(np_array)
print(f"Numpy np_array value: \n {np_array} \n")
print(f"Tensor x_np value: \n {x_np} \n")

np.multiply(np_array, 2, out=np_array)

print(f"Numpy np_array after * 2 operation: \n {np_array} \n")
print(f"Tensor x_np value after modifying numpy array: \n {x_np} \n")

Numpy np_array value: 
 [[1 2]
 [3 4]] 

Tensor x_np value: 
 tensor([[1, 2],
        [3, 4]]) 

Numpy np_array after * 2 operation: 
 [[2 4]
 [6 8]] 

Tensor x_np value after modifying numpy array: 
 tensor([[2, 4],
        [6, 8]]) 



In [ ]:
x_ones = torch.ones_like(x_data) # returns the properties of x_data
print(f"Ones Tensor: \n {x_ones} \n")

x_rand = torch.rand_like(x_data, dtype=torch.float) # Overrides the datatype of x_data
print(f"Random Tensor: \n {x_rand} \n")

Ones Tensor: 
 tensor([[1, 1],
        [1, 1]]) 

Random Tensor: 
 tensor([[0.3799, 0.0661],
        [0.8163, 0.2027]]) 



In [ ]:
shape = (2,3,)
rand_tensor = torch.rand(shape)
ones_tensor = torch.ones(shape)
zeros_tensor = torch.zeros(shape)

print(f"Random Tensor: \n {rand_tensor} \n")
print(f"Ones Tensor: \n {ones_tensor} \n")
print(f"Zeros Tensor: \n {zeros_tensor} \n")

Random Tensor: 
 tensor([[0.1645, 0.6582, 0.5805],
        [0.1835, 0.8423, 0.2670]]) 

Ones Tensor: 
 tensor([[1., 1., 1.],
        [1., 1., 1.]]) 

Zeros Tensor: 
 tensor([[0., 0., 0.],
        [0., 0., 0.]]) 



In [ ]:
tensor = torch.rand(3, 4)

print(f"Shape of tensor: {tensor.shape}")
print(f"Datatype of tensor: {tensor.dtype}")
print(f"Device tensor is stored on: {tensor.device}")


Shape of tensor: torch.Size([3, 4])
Datatype of tensor: torch.float32
Device tensor is stored on: cpu


In [ ]:
if torch.cuda.is_available():
    tensor = tensor.to('cuda')

: 

In [ ]:
tensor = torch.ones(4, 4)
print('First row: ',tensor[0])
print('First column: ', tensor[:, 0])
print('Last column:', tensor[..., -1])
tensor[:,1] = 0
print(tensor)

First row:  tensor([1., 1., 1., 1.])
First column:  tensor([1., 1., 1., 1.])
Last column: tensor([1., 1., 1., 1.])
tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]])


In [ ]:
t1 = torch.cat([tensor, tensor, tensor], dim=1)
print(t1)

tensor([[1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.],
        [1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.],
        [1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.],
        [1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.]])


In [ ]:
y1 = tensor @ tensor.T
y2 = tensor.matmul(tensor.T)

y3 = torch.rand_like(tensor)
torch.matmul(tensor, tensor.T, out=y3)

z1 = tensor * tensor
z2 = tensor.mul(tensor)

z3 = torch.rand_like(tensor)
torch.mul(tensor, tensor, out=z3)

tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]])

In [ ]:
agg = tensor.sum()
agg_item = agg.item()
print(agg_item, type(agg_item))

12.0 <class 'float'>


In [ ]:
print(tensor, "\n")
tensor.add_(5)
print(tensor)

tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]]) 

tensor([[6., 5., 6., 6.],
        [6., 5., 6., 6.],
        [6., 5., 6., 6.],
        [6., 5., 6., 6.]])


In [ ]:
t = torch.ones(5)
print(f"t: {t}")
n = t.numpy()
print(f"n: {n}")

t: tensor([1., 1., 1., 1., 1.])
n: [1. 1. 1. 1. 1.]


In [ ]:
t = torch.ones(5)
print(f"t: {t}")
n = t.numpy()
print(f"n: {n}")

t: tensor([1., 1., 1., 1., 1.])
n: [1. 1. 1. 1. 1.]


In [ ]:
t.add_(1)
print(f"t: {t}")
print(f"n: {n}")

t: tensor([2., 2., 2., 2., 2.])
n: [2. 2. 2. 2. 2.]


In [ ]:
n = np.ones(5)
t = torch.from_numpy(n)

In [ ]:
np.add(n, 1, out=n)
print(f"t: {t}")
print(f"n: {n}")

t: tensor([2., 2., 2., 2., 2.], dtype=torch.float64)
n: [2. 2. 2. 2. 2.]
