In [ ]:
import torch

## Tensor Arange

In [ ]:
torch.arange(5)

tensor([0, 1, 2, 3, 4])

In [ ]:
torch.arange(7.)

tensor([0., 1., 2., 3., 4., 5., 6.])

In [ ]:
torch.arange(2., 7.)

tensor([2., 3., 4., 5., 6.])

### Tensor Reshape
 Reshaping operations are extremely important because the layers in a neural network only accept dimensional specific inputs.

In [ ]:
t = torch.arange(12)
t = t.reshape([3, 4])
print(f"Shape: {t.shape}\n")
print(t)

Shape: torch.Size([3, 4])

tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])


The reshape function in PyTorch gives the output tensor with same values and number of elements as the input tensor, it only alters the shape of the output tensor.

In [ ]:
t.reshape(-1, 3)

tensor([[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8],
        [ 9, 10, 11]])

deduce the number of elements contained within the tensor. The number of elements inside a tensor (12 in our case) is equal to the product of the shape's component values.

In [ ]:
a = torch.arange(9)

r = torch.reshape(a, (3,3))
print(f'Reshaped tensor: {r.shape}\n')
print(f'Tensor: {r}\n')

b = torch.tensor([[45, 56], [27, 34]])
print(f"b: {b}\n")
torch.reshape(b, (-1,))

Reshaped tensor: torch.Size([3, 3])

Tensor: tensor([[0, 1, 2],
        [3, 4, 5],
        [6, 7, 8]])

b: tensor([[45, 56],
        [27, 34]])



tensor([45, 56, 27, 34])

In [ ]:
a = torch.randn(4, 3)
torch.prod(a, 0)

tensor([ 0.0241, -0.2109, -1.2540])

In [ ]:
torch.prod(a, 1)

tensor([ 0.6659,  0.8801, -0.0111, -0.9822])

In [ ]:
torch.prod(a, -1)

tensor([ 0.6659,  0.8801, -0.0111, -0.9822])

In [ ]:
a.numel()

9

In [ ]:
print(r)
r.reshape(9,-1)

tensor([[0, 1, 2],
        [3, 4, 5],
        [6, 7, 8]])


tensor([[0],
        [1],
        [2],
        [3],
        [4],
        [5],
        [6],
        [7],
        [8]])

For example, a 4D tensor of shape (batch_size, height, width, channels) cannot be fed into a fully connected layer that only accepts two dimensions. So we need to reshape the tensor to represent something like (batch_size, height * width * channels) which is a 2D tensor that can be used as an input to the fully connected layer.

In [ ]:
a = torch.rand(5, 4, 3, 2) # size (5, 4, 3, 2)
print(a.shape)
a_t = a.permute(0, 2, 3, 1) # size (5, 3, 2, 4)
print(a_t.shape)

torch.Size([5, 4, 3, 2])
torch.Size([5, 3, 2, 4])


In [ ]:
q = a.stride()
print(q)

(24, 6, 2, 1)


### Flatten Operation

The Flatten operation is used to convert a multi-dimensional tensor into a one-dimensional tensor. This is done by taking all the elements of the tensor and arranging them in a single dimension.

For example, if we have a tensor of shape (2, 3, 4), applying the Flatten operation would result in a tensor of shape (24,), which is basically a product of the individual elements.

Pytorch provides `view` & `flatten` functions to flatten tensors.

*view*() reshapes the tensor without copying memory

In [ ]:
x = torch.randn(16, 5, 5, 3)
print(f'Original shape: {x.shape}')

x = x.view(16, 75) # ~ (16, 5*5*3)
print(f'Flattened shape: {x.shape}')

Original shape: torch.Size([16, 5, 5, 3])
Flattened shape: torch.Size([16, 75])


Using `flatten` function

In [ ]:
x = torch.randn(16, 5, 5, 3)
print(f'Original shape: {x.shape}')

x = x.flatten()
print(f'Flattened shape: {x.shape}')

Original shape: torch.Size([16, 5, 5, 3])
Flattened shape: torch.Size([1200])


This method creates a tensor x of shape of (16, 5, 5, 3) and then uses flatten function to reshape into 1D tensor. This gives us a tensor of shape (24,), which is product of dimensions of original tensor.

### Squeeze Operation
Removes dimensions of size 1 from a tensor. Useful when you have a tensor with unnecessary dimensions that you want to get rid off.

In [ ]:
x = torch.randn(3, 1, 1, 5)
print(f'Original shape: {x.shape}')

x = x.squeeze()
print(f'Squeezed shape: {x.shape}')

Original shape: torch.Size([3, 1, 1, 5])
Squeezed shape: torch.Size([3, 5])


An advantage of this method is, the tensor can be unsqueezed again.

In [ ]:
x = torch.randn(3, 5)
x = x.unsqueeze(1)
x = x.unsqueeze(2)
print(f'Unsqueezed shape: {x.shape}')

Unsqueezed shape: torch.Size([3, 1, 1, 5])


 it is possible to flatten only specific parts of a tensor. For example, suppose we have a tensor of shape [2,1,28,28] for a CNN. This means that we have a batch of 2 grayscale images with height and width dimensions of 28 x 28, respectively.

Here, we can specifically flatten the two images. To get the following shape: [2,1,784]. We could also squeeze off the channel axes to get the following shape: [2,784].

In [ ]:
###  Concatenating tensors

t1 = torch.tensor([
    [1,2],
    [3,4]
])
t2 = torch.tensor([
    [5,6],
    [7,8]
])

Combine t1 and t2 row-wise (axis-0) in the following way

In [ ]:
torch.cat((t1, t2), dim=0)

tensor([[1, 2],
        [3, 4],
        [5, 6],
        [7, 8]])

Combine them column-wise (axis-1) like this:

In [ ]:
torch.cat((t1, t2), dim=1)

tensor([[1, 2, 5, 6],
        [3, 4, 7, 8]])

In [ ]:
# https://learn.microsoft.com/en-us/training/modules/intro-machine-learning-pytorch/2-tensors

%matplotlib inline
import torch
import numpy as np

In [ ]:
np_array = np.array(data)
x_np = torch.from_numpy(np_array)
print(f"Numpy np_array value: \n {np_array} \n")
print(f"Tensor x_np value: \n {x_np} \n")

np.multiply(np_array, 2, out=np_array)

print(f"Numpy np_array after * 2 operation: \n {np_array} \n")
print(f"Tensor x_np value after modifying numpy array: \n {x_np} \n")

Numpy np_array value: 
 [[1 2]
 [3 4]] 

Tensor x_np value: 
 tensor([[1, 2],
        [3, 4]]) 

Numpy np_array after * 2 operation: 
 [[2 4]
 [6 8]] 

Tensor x_np value after modifying numpy array: 
 tensor([[2, 4],
        [6, 8]]) 



In [ ]:
x_ones = torch.ones_like(x_data) # returns the properties of x_data
print(f"Ones Tensor: \n {x_ones} \n")

x_rand = torch.rand_like(x_data, dtype=torch.float) # Overrides the datatype of x_data
print(f"Random Tensor: \n {x_rand} \n")

Ones Tensor: 
 tensor([[1, 1],
        [1, 1]]) 

Random Tensor: 
 tensor([[0.3799, 0.0661],
        [0.8163, 0.2027]]) 



In [ ]:
shape = (2,3,)
rand_tensor = torch.rand(shape)
ones_tensor = torch.ones(shape)
zeros_tensor = torch.zeros(shape)

print(f"Random Tensor: \n {rand_tensor} \n")
print(f"Ones Tensor: \n {ones_tensor} \n")
print(f"Zeros Tensor: \n {zeros_tensor} \n")

Random Tensor: 
 tensor([[0.1645, 0.6582, 0.5805],
        [0.1835, 0.8423, 0.2670]]) 

Ones Tensor: 
 tensor([[1., 1., 1.],
        [1., 1., 1.]]) 

Zeros Tensor: 
 tensor([[0., 0., 0.],
        [0., 0., 0.]]) 



In [ ]:
tensor = torch.rand(3, 4)

print(f"Shape of tensor: {tensor.shape}")
print(f"Datatype of tensor: {tensor.dtype}")
print(f"Device tensor is stored on: {tensor.device}")


Shape of tensor: torch.Size([3, 4])
Datatype of tensor: torch.float32
Device tensor is stored on: cpu


In [ ]:
if torch.cuda.is_available():
    tensor = tensor.to('cuda')

: 

In [ ]:
tensor = torch.ones(4, 4)
print('First row: ',tensor[0])
print('First column: ', tensor[:, 0])
print('Last column:', tensor[..., -1])
tensor[:,1] = 0
print(tensor)

First row:  tensor([1., 1., 1., 1.])
First column:  tensor([1., 1., 1., 1.])
Last column: tensor([1., 1., 1., 1.])
tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]])


In [ ]:
t1 = torch.cat([tensor, tensor, tensor], dim=1)
print(t1)

tensor([[1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.],
        [1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.],
        [1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.],
        [1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.]])


In [ ]:
print(tensor @ tensor.T)
print(tensor.matmul(tensor.T))

tensor([[3., 3., 3., 3.],
        [3., 3., 3., 3.],
        [3., 3., 3., 3.],
        [3., 3., 3., 3.]])
tensor([[3., 3., 3., 3.],
        [3., 3., 3., 3.],
        [3., 3., 3., 3.],
        [3., 3., 3., 3.]])


In [ ]:
y3 = torch.rand_like(tensor)
print(y3)
torch.matmul(tensor, tensor.T, out=y3)

tensor([[0.9013, 0.8849, 0.2794, 0.5341],
        [0.6592, 0.7621, 0.0658, 0.0542],
        [0.3638, 0.6425, 0.8752, 0.5873],
        [0.0620, 0.0884, 0.9533, 0.9562]])


tensor([[3., 3., 3., 3.],
        [3., 3., 3., 3.],
        [3., 3., 3., 3.],
        [3., 3., 3., 3.]])

In [ ]:
print(tensor * tensor)
print(tensor.mul(tensor))

tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]])
tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]])


In [ ]:
z3 = torch.rand_like(tensor)
torch.mul(tensor, tensor, out=z3)

tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]])

In [ ]:
agg = tensor.sum()
agg_item = agg.item()
print(agg_item, type(agg_item))

12.0 <class 'float'>


In [ ]:
print(tensor, "\n")
tensor.add_(5)
print(tensor)

tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]]) 

tensor([[6., 5., 6., 6.],
        [6., 5., 6., 6.],
        [6., 5., 6., 6.],
        [6., 5., 6., 6.]])


In [ ]:
t = torch.ones(5)
print(f"t: {t}")
n = t.numpy()
print(f"n: {n}")

t: tensor([1., 1., 1., 1., 1.])
n: [1. 1. 1. 1. 1.]


In [ ]:
t.add_(1)
print(f"t: {t}")
print(f"n: {n}")

t: tensor([2., 2., 2., 2., 2.])
n: [2. 2. 2. 2. 2.]


In [ ]:
n = np.ones(5)
t = torch.from_numpy(n)

NameError: name 'np' is not defined

In [ ]:
np.add(n, 1, out=n)
print(f"t: {t}")
print(f"n: {n}")

t: tensor([2., 2., 2., 2., 2.], dtype=torch.float64)
n: [2. 2. 2. 2. 2.]


### Outer

https://pytorch.org/docs/stable/generated/torch.outer.html


In [ ]:
t1 = torch.arange(1., 7.)
t2 = torch.arange(1., 4.)

print(t1, t2)

torch.outer(t1, t2)

tensor([1., 2., 3., 4., 5., 6.]) tensor([1., 2., 3.])


tensor([[ 1.,  2.,  3.],
        [ 2.,  4.,  6.],
        [ 3.,  6.,  9.],
        [ 4.,  8., 12.],
        [ 5., 10., 15.],
        [ 6., 12., 18.]])

In [ ]:
torch.full((2, 3), 3.141592)

tensor([[3.1416, 3.1416, 3.1416],
        [3.1416, 3.1416, 3.1416]])

In [ ]:
b = torch.randn(4, 6)
print(b)
torch.triu(b, diagonal=1)

tensor([[-1.7552,  0.9201, -1.1096,  0.4242, -1.5970,  0.8829],
        [ 0.2008,  0.2098,  0.6898, -0.9361, -0.3924, -1.3563],
        [-1.4787,  1.9486, -0.6433, -0.2257,  0.9296, -0.5592],
        [ 0.0939, -0.4387, -0.9124, -1.3092, -0.5978,  1.5021]])


tensor([[ 0.0000,  0.9201, -1.1096,  0.4242, -1.5970,  0.8829],
        [ 0.0000,  0.0000,  0.6898, -0.9361, -0.3924, -1.3563],
        [ 0.0000,  0.0000,  0.0000, -0.2257,  0.9296, -0.5592],
        [ 0.0000,  0.0000,  0.0000,  0.0000, -0.5978,  1.5021]])

In [ ]:
b = torch.randn(4, 6)
print(b)
torch.triu(b, diagonal=0)

tensor([[ 0.2072, -0.3390, -0.8492, -0.9737, -1.5321, -0.4971],
        [ 1.5928, -0.0409, -0.5222, -0.9015, -0.2431, -2.5392],
        [-0.1135,  0.2626, -1.1789,  0.3271,  1.6456, -0.7584],
        [-0.6306, -0.0679, -2.0453,  0.1281, -1.2626, -0.5594]])


tensor([[ 0.2072, -0.3390, -0.8492, -0.9737, -1.5321, -0.4971],
        [ 0.0000, -0.0409, -0.5222, -0.9015, -0.2431, -2.5392],
        [ 0.0000,  0.0000, -1.1789,  0.3271,  1.6456, -0.7584],
        [ 0.0000,  0.0000,  0.0000,  0.1281, -1.2626, -0.5594]])

In [ ]:
a = torch.tensor([1, 2, 3])
b = torch.tensor([4, 5, 6])
torch.hstack((a,b))

tensor([1, 2, 3, 4, 5, 6])

In [ ]:
a = torch.tensor([[1],[2],[3]])
b = torch.tensor([[4],[5],[6]])
torch.hstack((a,b))

tensor([[1, 4],
        [2, 5],
        [3, 6]])