In [2]:
import torch

In [3]:
class TinyModel(torch.nn.Module):
    
    def __init__(self):

        super(TinyModel, self).__init__()

        self.linear1 = torch.nn.Linear(100, 200)
        self.activation = torch.nn.ReLU()
        self.linear2 = torch.nn.Linear(200, 10)
        self.softmax = torch.nn.Softmax()
    
    def forward(self, x):
        x = self.linear1(x)
        x = self.activation(x)
        x = self.linear2(x)
        x = self.softmax(x)

        return x
    
tinymodel = TinyModel()

In [4]:
print(tinymodel)

TinyModel(
  (linear1): Linear(in_features=100, out_features=200, bias=True)
  (activation): ReLU()
  (linear2): Linear(in_features=200, out_features=10, bias=True)
  (softmax): Softmax(dim=None)
)


In [5]:
print(tinymodel.linear2)

Linear(in_features=200, out_features=10, bias=True)


In [6]:
for param in tinymodel.parameters():
    print(param)

Parameter containing:
tensor([[ 0.0065,  0.0837, -0.0036,  ..., -0.0227, -0.0059, -0.0494],
        [ 0.0505,  0.0186, -0.0473,  ..., -0.0804, -0.0734,  0.0803],
        [-0.0111,  0.0292, -0.0764,  ...,  0.0578,  0.0562,  0.0787],
        ...,
        [-0.0540,  0.0151, -0.0969,  ...,  0.0068,  0.0991,  0.0408],
        [-0.0527,  0.0420,  0.0576,  ..., -0.0739, -0.0351,  0.0853],
        [ 0.0508, -0.0593, -0.0055,  ..., -0.0075, -0.0877,  0.0137]],
       requires_grad=True)
Parameter containing:
tensor([ 0.0270,  0.0923,  0.0428,  0.0615, -0.0096,  0.0420,  0.0284, -0.0097,
         0.0174, -0.0739, -0.0398,  0.0370, -0.0380, -0.0298,  0.0996, -0.0921,
        -0.0445,  0.0760,  0.0166,  0.0058,  0.0333, -0.0694,  0.0507, -0.0312,
         0.0520, -0.0926,  0.0238, -0.0366, -0.0247, -0.0038, -0.0486, -0.0339,
        -0.0433, -0.0678, -0.0422, -0.0931, -0.0262, -0.0608,  0.0077, -0.0620,
        -0.0998,  0.0120, -0.0109,  0.0907,  0.0349,  0.0463, -0.0971,  0.0986,
        -0.0961

In [7]:
lin = torch.nn.Linear(3, 2)
x = torch.rand(1, 3)
print(x)

tensor([[0.9333, 0.2029, 0.4908]])


In [8]:
for param in lin.parameters():
    print(param)

Parameter containing:
tensor([[ 0.2974,  0.4080,  0.3181],
        [ 0.3333, -0.4913, -0.2258]], requires_grad=True)
Parameter containing:
tensor([0.5570, 0.3077], requires_grad=True)


In [9]:
y = lin(x)
print(y)

tensor([[1.0734, 0.4083]], grad_fn=<AddmmBackward0>)
